In [1]:
import numpy as np
from fonctions_projets import *
import time
import matplotlib.pyplot as plt

In [2]:
def test(n,step):
    #parameter of loi nomral
    m=1000
    #for each size of solutions-set, calculate the average time of 50 trials
    nb_trial=50
    x=[]
    temps_moyen_naif=[]
    temps_moyen_lex=[]
    for i in range(200,n+1,step):
        #solutions set
        x.append(i)
        tmp_naif = 0
        tmp_lex =0
        for j in range(nb_trial):
            test_set = vecteur_alea(n,m)
            time_naif_start = time.time()
            d1=recherche_exhaustif(test_set,True)
            time_naif_end = time.time()
            tmp_naif += time_naif_end-time_naif_start
            
            time_lex_start = time.time()
            d2=recherche_lexicographique(test_set, True)
            time_lex_end = time.time()
            tmp_lex += time_lex_end-time_lex_start
            if(len(set(d1).difference(set(d2)))!=0):
                raise Exception("error in algorithme!")
        temps_moyen_naif.append(tmp_naif/nb_trial)
        temps_moyen_lex.append(tmp_lex/nb_trial)
    
    plot_figure(x,temps_moyen_naif,temps_moyen_lex)
    

In [3]:
def plot_figure(x,tn,tl):
    plt.title("La courbe du temps d'exécution")
    plt.xlabel("taille d'ensemle des solutions")
    plt.ylabel("temps")
    plt.plot(x,tn,color='r',label="recherche exhaustive")
    plt.plot(x,tl,color='b',label="recherche lexicographique")
    plt.legend()

## Test la programmation dynamique

In [4]:
test = np.array([1,4,2,3,5,2,2,2,3,1,2,5,3,4]).reshape((-1,2))

In [5]:
ens_opt=prog_dynamique(test,3,True)

In [6]:
ens_opt

array([[1., 1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.]])

In [7]:
image(test,ens_opt)

array([[ 5,  9],
       [ 6,  7],
       [ 7,  6],
       [10,  5]])

## Test la procedure en deux phases

In [8]:
minimax_deux_temps(test,3,0.4,0.7,True)

(array([6, 7]), array([1., 0., 0., 1., 1., 0., 0.]))