In [1]:
import numpy as np
from fonctions import *
#from pg import *
import time
import matplotlib.pyplot as plt

In [2]:
test=np.array([1,4,2,3,5,2,2,2,3,1,2,5,3,4])

In [3]:
test=test.reshape((-1,2))

In [4]:
test

array([[1, 4],
       [2, 3],
       [5, 2],
       [2, 2],
       [3, 1],
       [2, 5],
       [3, 4]])

In [5]:
result=prog_dynamique(test,3,True)

init [array([0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0.]), [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
1 0
1 1
[1. 0. 0. 0. 0. 0. 0.] [0. 0. 0. 0. 0. 0. 0.]
(1, 7)
G 1 0 [[1. 0. 0. 0. 0. 0. 0.]]
F 0 0 [[0. 1. 0. 0. 0. 0. 0.]]
ens_index [[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
shape (2, 7)
images [[1 4]
 [2 3]]
1 2
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]] [0. 0. 0. 0. 0. 0. 0.]
(1, 7)
G 1 1 [[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
F 0 1 [[0. 0. 1. 0. 0. 0. 0.]]
ens_index [[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]]
shape (3, 7)
images [[1 4]
 [2 3]
 [5 2]]
1 3
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]] [0. 0. 0. 0. 0. 0. 0.]
(1, 7)
G 1 2 [[1. 0. 0. 0. 0. 0. 0.]
 [0

In [6]:
result

array([[1., 1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.]])

In [7]:
test=vecteur_alea(10000,4)

In [8]:
d2=recherche_lexicographique(test,True)

In [9]:
d2

array([9200, 6613, 5901, 3171, 6512, 7047, 7461, 2171, 3791, 2673])

In [14]:
def recherche(ens_vecteurs,MIN):
	res = []
	for i in range(len(ens_vecteurs)):
		state = False
		for j in range(len(ens_vecteurs)):
			if compare(ens_vecteurs[i,:],ens_vecteurs[j,:],MIN):
				state = True

		if state == False:
			res.append(i)
	return res

In [15]:
recherche(test,True)

[2171, 2673, 3171, 3791, 5901, 6512, 6613, 7047, 7461, 9200]

In [16]:
d1=d2

In [17]:
np.array([2171, 2673, 3171, 3791, 5901, 6512, 6613, 7047, 7461, 9200])==d2

array([False, False, False, False, False, False, False, False, False,
       False])