In [1]:
import numpy as np
from fonctions import *
#from pg import *
import time
import matplotlib.pyplot as plt

In [2]:
test=np.array([1,4,2,3,5,2,2,2,3,1,2,5,3,4])

In [3]:
test=test.reshape((-1,2))

In [5]:
index=prog_dynamique(test,3,True)

In [6]:
result = image(test,index)

In [7]:
result

array([[ 5,  9],
       [ 6,  7],
       [ 7,  6],
       [10,  5]])

In [8]:
minimax_deux_temps(test,3,0,1,True)

(array([[[6, 7],
         [7, 6]]]),
 array([[[1., 0., 0., 1., 1., 0., 0.],
         [0., 1., 0., 1., 1., 0., 0.]]]))

In [22]:
def transform(ens_vect,alpha_min,alpha_max):
    nb_vect,dim = ens_vect.shape
    ens_trans = np.zeros((nb_vect,dim))
    for i in range(nb_vect):
        x,y = ens_vect[i,:]
        x_trans = alpha_min*x+(1-alpha_min)*y
        y_trans = alpha_max*x+(1-alpha_max)*y
        ens_trans[i,:]= np.array([x_trans,y_trans])
    return ens_trans

In [23]:
transform(test,0.5,0.8)

array([[2.5, 1.6],
       [2.5, 2.2],
       [3.5, 4.4],
       [2. , 2. ],
       [2. , 2.6],
       [3.5, 2.6],
       [3.5, 3.2]])

In [54]:
def minimax_I_dominance(ens_vect,k,alpha_min,alpha_max,MIN=True):
    ens_trans = transform(ens_vect,alpha_min,alpha_max)
    index = prog_dynamique(ens_trans,k,MIN)
    images = image(ens_trans,index)
    images_real = image(ens_vect,index)
    #print(images)
    #ens_trans = transform(images,alpha_min,alpha_max)
    points_minimax =[]
    for i in range(images.shape[0]):
        y1,y2 = images_real[i,:]
        if y1<=y2:
            points_minimax.append(images[i,0])
        else:
            points_minimax.append(images[i,1])
            
    #print(points_minimax)
    minimax = np.min(np.array(points_minimax))
    #print(minimax)
    index_point_minimax = np.where(np.array(points_minimax)==minimax)
    return images[index_point_minimax,:], index[index_point_minimax,:]   

In [55]:
minimax_I_dominance(test,3,0,1,True)

(array([[[6., 7.],
         [7., 6.]]]),
 array([[[0., 1., 0., 1., 1., 0., 0.],
         [1., 0., 0., 1., 1., 0., 0.]]]))