In [1]:
import numpy as np
from fonctions import *
import time
import matplotlib.pyplot as plt

In [2]:
test=np.array([1,4,2,3,5,2,2,2,3,1,2,5,3,4])

In [3]:
test=test.reshape((-1,2))

In [4]:
index=prog_dynamique(test,3,True)

In [5]:
result = image(test,index)

In [6]:
result

array([[ 5,  9],
       [ 6,  7],
       [ 7,  6],
       [10,  5]])

In [7]:
minimax_deux_temps(test,3,0,1,True)

(array([[[6, 7],
         [7, 6]]]),
 7,
 array([[[1., 0., 0., 1., 1., 0., 0.],
         [0., 1., 0., 1., 1., 0., 0.]]]))

In [8]:
transform(test,0.5,0.8)

array([[2.5, 1.6],
       [2.5, 2.2],
       [3.5, 4.4],
       [2. , 2. ],
       [2. , 2.6],
       [3.5, 2.6],
       [3.5, 3.2]])

In [9]:
minimax_I_dominance(test,3,0,1,True)

(array([[[7, 6],
         [6, 7]]]),
 7.0,
 array([[[0., 1., 0., 1., 1., 0., 0.],
         [1., 0., 0., 1., 1., 0., 0.]]]))