In [1]:
import numpy as np
from fonctions import *
import time
import matplotlib.pyplot as plt

In [2]:
test=vecteur_alea(4,10)

In [4]:
recherche_exhaustif(test,MIN=True)

array([0, 2])

In [5]:
tri_lexicographique(test)

array([0, 3, 2, 1])

In [6]:
recherche_lexicographique(test, MIN=True)

array([0, 2])

In [7]:
minimax_deux_temps(test,k=1,alpha_min=0.2,alpha_max=0.5,MIN=True)

(array([[[ 9.34453515, 10.34922359]]]),
 10.148285902000001,
 array([[[0., 0., 1., 0.]]]))

In [8]:
minimax_I_dominance(test,k=1,alpha_min=0.2,alpha_max=0.5,MIN=True)

(array([[[ 9.34453515, 10.34922359]]]),
 10.148285902000001,
 array([[[0., 0., 1., 0.]]]))